Dashboard Sidebar and Animation
Nomi-Technologies/menu-dashboard pull request #32
Opened 2020-09-21 06:33 UTC by konradscheng

https://app.asana.com/0/1170551505628299/1189828027572753/f

2020-09-25 15:19 UTC, Tony1023 requested changes
Thanks for the PR!

Side bar and its expand/collapse animations looks great on my computer, but there are still a few things we might want to take a look. I left some comments below :)

2020-09-25 15:19 UTC, Tony1023 commented on src/components/dashboard/sidebar/sidebar-layout.js
> +  width: ${ props => props.sidebarOpen ? "13%" : "5%"};
Would you think that it's better & easy to change pixel values for the sidebar width?

2020-09-25 15:19 UTC, Tony1023 commented on src/components/grid.js
> +   max-width: 88%;
Ditto

2020-09-25 15:19 UTC, Tony1023 commented on src/components/dashboard/sidebar/sidebar-layout.js
> +  margin-bottom: 5%;
Let's add cursor: pointer ?

2020-09-25 15:19 UTC, Tony1023 commented on src/pages/dashboard/restaurant.js
> +  <SidebarLayout>
Are we missing an entry point for this page?

2020-09-25 15:19 UTC, Tony1023 commented on src/pages/dashboard/personal.js
> +  <SidebarLayout>
This page is mysteriously vertically scrollable...

2020-09-27 23:09 UTC, cchyung approved these changes

2020-09-27 23:09 UTC, merged